[book]
title = "Documentation Theoretical Computeur"
authors = ["Jonas Facon"]
language = "fr"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[preprocessor.katex]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
